routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::group(
    [
        'prefix' => 'task',
        'as' => 'task.',
        'namespace' => 'Task',
    ],
    function () {
        Route::get('/create', 'TaskController@create')->name('create');
        Route::post('/create', 'TaskController@store')->name('create.store');
        Route::get('/edit/{task}', 'TaskController@edit')->middleware('auth', 'can:admin')->name('edit');
        Route::post('/edit/{task}', 'TaskController@update')->middleware('auth', 'can:admin')->name('edit.update');
    }
);

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Tasks;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        //$query = Tasks::with("user")->orderByDesc('id');
        $query = Tasks::join('users', 'tasks.user_id', '=', 'users.id')/*->orderByDesc('tasks.id')*/;
        if (($value = $request->get('status'))!=NULL) {
            $query->where('status', $value);
        }
        /*$query->whereHas("user", function($query) use ($request)
        {
            if (!empty($value = $request->get('name'))) {
                //$query->where('users.name', 'like', '%' . $value . '%');
            }
            if (!empty($value = $request->get('email'))) {
                $query->where('users.email', 'like', '%' . $value . '%');
            }

        });*/

        if (!empty($value = $request->get('name'))) {
            $query->orderBy('users.name', $value);
        }
        if (!empty($value = $request->get('email'))) {
            $query->orderBy('users.email', $value);
        }
        $tasks = $query->paginate(3);
        return view('home', compact('tasks'));
    }
}

app/Http/Controllers/Task/TaskController.php
<?php

namespace App\Http\Controllers\Task;

use App\Http\Controllers\Controller;
use App\Entity\User;
use App\Entity\Tasks;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function create()
    {
        $users = User::orderByDesc('id')->get();
        return view('task.create',compact('users'));
    }
    public function store(Request $request)
    {

        $this->validate($request, [
            'text' => 'required|string',
            'user' => 'required|exists:users,id',
        ]);
        Tasks::create([
            'text' => $request['text'],
            'user_id' => $request['user'],
            'status' => 0
        ]);

        return redirect()->route('home');
    }

    public function edit(Tasks $task)
    {
        return view('task.edit',compact('task'));
    }
    public function update(Request $request, Tasks $task)
    {
        $request['status']=$request['status']?1:0;
        $this->validate($request, [
            'text' => 'required|string',
            'status' => 'required|boolean',
        ]);

        $task->update([
            'text' => $request['text'],
            'status' => $request['status'],
        ]);

        return redirect()->route('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('search')
    <div class="search-bar pt-3">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <form action="{{ route('home') }}" method="GET">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    Name
                                    <!--<input type="text" class="form-control" name="name"
                                           value="{{ request('name') }}" placeholder="Filter for name">-->
                                        <select id="name" class="form-control" name="name">
                                            <option value=""></option>
                                            <option value="asc"{{ "asc" == request('name') ? ' selected' : '' }}>asc</option>
                                            <option value="desc"{{ "desc" == request('name') ? ' selected' : '' }}>desc</option>
                                        </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    Email
                                    <!--<input type="text" class="form-control" name="email"
                                           value="{{ request('email') }}" placeholder="Filter for email">-->
                                    <select id="email" class="form-control" name="email">
                                        <option value=""></option>
                                        <option value="asc"{{ "asc" == request('email') ? ' selected' : '' }}>asc</option>
                                        <option value="desc"{{ "desc" == request('email') ? ' selected' : '' }}>desc</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    Status
                                    <select id="status" class="form-control" name="status">
                                        <option value=""></option>

                                            <option value="0"{{ "0" === request('status') ? ' selected' : '' }}>{{ 0 }}</option>
                                            <option value="1"{{ "1" === request('status') ? ' selected' : '' }}>{{ 1 }}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <div class="form-group">
                                    <button class="btn btn-light border" type="submit">Search</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3" style="text-align: right">
                    <p><a href="{{ route('task.create') }}" class="btn btn-success"><span class="fa fa-plus"></span>
                            Add task</a></p>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Text</th>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($tasks as $task)
            <tr>
                <td>{{ $task->text }}</td>
                <td>{{ $task->user->name }}</td>
                <td>{{ $task->user->email }}</td>
                <td>{{ $task->status }}</td>
                <td><a href="{{ route('task.edit', $task) }}">Edit</a></td>
            </tr>
        @endforeach

        </tbody>
    </table>
    {{ $tasks->links() }}
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Adverts</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css', 'build') }}" rel="stylesheet">
</head>
<body id="app">
<header>
    <nav class="navbar navbar-expand-mdп navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                BeeJee
            </a>
        </div>
    </nav>
    @yield('search')
</header>
<main class="app-content py-3">
    <div class="container">
        @include('layouts.partials.flash')
        @yield('content')
    </div>
</main>
<footer>
    <div class="container">
        <div class="border-top pt-3">
            <p>&copy; {{ date('Y') }} - BeeJee</p>
        </div>
    </div>
</footer>

<!-- Scripts -->
<script src="{{ mix('js/app.js', 'build') }}"></script>
</body>
</html>

resources/views/layouts/partials/flash.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

@if (session('info'))
    <div class="alert alert-info">
        {{ session('info') }}
    </div>
@endif

resources/views/task/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{ route('task.create.store') }}">
        @csrf
        <div class="form-group">
            <label for="text" class="col-form-label">Text</label>
            <input id="name" class="form-control{{ $errors->has('text') ? ' is-invalid' : '' }}" name="text" value="{{ old('text') }}" required>
            @if ($errors->has('text'))
                <span class="invalid-feedback"><strong>{{ $errors->first('text') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="parent" class="col-form-label">User</label>
            <select id="parent" class="form-control{{ $errors->has('user') ? ' is-invalid' : '' }}" name="user" required>
                @foreach ($users as $user)
                    <option value="{{ $user->id }}"{{ $user->id == old('user') ? ' selected' : '' }}>
                        {{ $user->name }}
                    </option>
                @endforeach;
            </select>
            @if ($errors->has('user'))
                <span class="invalid-feedback"><strong>{{ $errors->first('user') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/task/edit.blade.php
@extends('layouts.app')
@section('content')
    <form method="POST" action="{{ route('task.edit.update',$task) }}">
        @csrf
        <div class="form-group">
            <label for="text" class="col-form-label">Text</label>
            <input id="text" class="form-control{{ $errors->has('text') ? ' is-invalid' : '' }}" name="text" value="{{ old('text',$task->text) }}" required>
            @if ($errors->has('text'))
                <span class="invalid-feedback"><strong>{{ $errors->first('text') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input id="status" name="status" type="checkbox" {{ old('status', $task->status) ? 'checked' : '' }}> Status
                </label>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection